spring.application.name=javarestapi
# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/javaspring
spring.datasource.username=postgres
spring.datasource.password=Daotunglam28
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Server Port (optional)
server.port=8080